apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
type: Opaque
data:
  api-token: ""
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email:
            apiTokenSecretRef:
              name: cloudflare-credentials
              key: api-token