{{- if .Values.dev.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.name" . }}-conf-templates
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
data:
{{ tpl (.Files.Glob (printf "dev/*" )).AsConfig . | indent 2 }}
{{- end }}