apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.fullname" . }}
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9083
      targetPort: 9083
      protocol: TCP
      name: thrift
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
