name: Build and Publish Docker image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image'
        required: true
        type: choice
        options:
          - kyuubi
          - hive
          - spark
      latest:
        description: 'True to tag with latest'
        required: true
        type: boolean
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.image }}
          tags: |
            type=raw,value=latest,enable=${{ inputs.latest }}
            type=raw,value=${{ inputs.version }},enable=${{ inputs.latest }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ inputs.image }}/${{ inputs.version }}
          file: ./docker/${{ inputs.image }}/${{ inputs.version }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ inputs.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true